AWSTemplateFormatVersion: "2010-09-09"
Description: SageMaker Workshop - CloudFormation Template

Resources:
  NotebookRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"

  NotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.t2.large"
      RoleArn: !GetAtt NotebookRole.Arn
      
  MammographyBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "mammography-workshop-files-${AWS::Region}-${AWS::AccountId}"

Outputs:
  Instance:
    Description: SageMaker Notebook Instance.
    Value: !Ref NotebookInstance
  Role:
    Description: SageMaker Notebook Instance Role.
    Value: !GetAtt NotebookRole.Arn
  MammographyBucket:
    Description: Bucket for storing the files needed and produced by this workshop.
    Value: !Ref MammographyBucket
